micronaut:
  application:
    name: Kafka Consumer App
  server:
    port: 8180
kafka:
  bootstrap:
    servers: localhost:9092
  consumers:
    default:
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true
    company-consumer-group:
      key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true